function RMS = RMS_test(Torques_data, Joint_No, param_vec, g)
    err_array =[];
    for i = 1:size(Torques_data,3)
        measure_torque = Torques_data(Joint_No,2,i);
        R_pos = analytical_regressor_pos_mat(g,...
                                         Torques_data(1,1,i),...
                                         Torques_data(2,1,i),...
                                         Torques_data(3,1,i),...
                                         Torques_data(4,1,i),...
                                         Torques_data(5,1,i),...
                                         Torques_data(6,1,i));
        R_neg = analytical_regressor_neg_mat(g,...
                                             Torques_data(1,1,i),...
                                             Torques_data(2,1,i),...
                                             Torques_data(3,1,i),...
                                             Torques_data(4,1,i),...
                                             Torques_data(5,1,i),...
                                             Torques_data(6,1,i));
        predict_torque = (R_pos*param_vec + R_neg*param_vec)/2;
        err_array(end+1) = measure_torque -predict_torque(Joint_No);
    end
    RMS = sqrt(sum(err_array.^2)/size(Torques_data,3));
end

