function bool_Regressor_Mat = analytical_bool_regressor_mat
%ANALYTICAL_BOOL_REGRESSOR_MAT
%    BOOL_REGRESSOR_MAT = ANALYTICAL_BOOL_REGRESSOR_MAT

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    17-Oct-2019 18:15:27

bool_Regressor_Mat = reshape([0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0],[7,10]);
